FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN pip install mlflow psycopg2-binary boto3

# Expose MLflow port
EXPOSE 5000

# Run MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlartifacts"]
